export const initialCandidates = [
  {
    id: "cand_1",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    target_role: "Data Scientist / AI Engineer",
    summary: "Experienced Data Scientist with 3+ years specializing in Python, Machine Learning, Deep Learning, SQL, and NLP. Passionate about building predictive models and AI systems.",
    skills: ["Python", "Machine Learning", "SQL", "Deep Learning", "TensorFlow", "Pandas", "Scikit-Learn", "NLP", "Git"],
    experience_years: 3.5,
    education: "B.Tech in Computer Science - IIT Bombay (2021)",
    experience: [
      { company: "TechCraft Labs", role: "Junior Data Scientist", duration: "2022 - Present", description: "Developed NLP models for customer sentiment and reduced churn by 18%." },
      { company: "DataSolutions Inc", role: "AI Intern", duration: "2021 - 2022", description: "Built tabular prediction models using XGBoost and Random Forest." }
    ],
    preferred_location: "Bangalore",
    preferred_work_type: "Remote",
    target_salary_min: 1600000,
    profile_completion: 85,
    resume_file: "Priya_Sharma_Resume_DataScientist.pdf"
  },
  {
    id: "cand_2",
    name: "Rohan Verma",
    email: "rohan.verma@example.com",
    target_role: "Full Stack Engineer",
    summary: "Full Stack Developer proficient in React, Node.js, Express, PostgreSQL, and AWS. 4 years of hands-on software development experience.",
    skills: ["React", "Node.js", "TypeScript", "Express", "PostgreSQL", "MongoDB", "AWS", "Docker", "Tailwind CSS"],
    experience_years: 4.0,
    education: "B.E. in Information Technology - RVCE Bangalore (2020)",
    experience: [
      { company: "CloudScale India", role: "Senior Full Stack Dev", duration: "2022 - Present", description: "Led web team building SaaS analytics portal handling 50k DAU." }
    ],
    preferred_location: "Bangalore",
    preferred_work_type: "Hybrid",
    target_salary_min: 1800000,
    profile_completion: 90,
    resume_file: "Rohan_Verma_FullStack_Resume.pdf"
  },
  {
    id: "cand_3",
    name: "Aanya Patel",
    email: "aanya.patel@example.com",
    target_role: "Machine Learning Engineer",
    summary: "ML Engineer focused on computer vision and MLOps. Strong math and Python programming base with PyTorch and MLflow expertise.",
    skills: ["Python", "PyTorch", "Computer Vision", "Docker", "MLOps", "Kubernetes", "OpenCV", "FastAPI"],
    experience_years: 2.5,
    education: "M.Tech in Data Science - IIIT Hyderabad (2022)",
    experience: [
      { company: "VisionAI India", role: "ML Engineer", duration: "2022 - Present", description: "Deployed real-time object detection pipelines on edge GPUs." }
    ],
    preferred_location: "Hyderabad",
    preferred_work_type: "Remote",
    target_salary_min: 2000000,
    profile_completion: 95,
    resume_file: "Aanya_Patel_ML_Engineer.pdf"
  },
  {
    id: "cand_4",
    name: "Vikram Malhotra",
    email: "vikram.m@example.com",
    target_role: "Backend Engineer",
    summary: "High-performance backend engineer with expertise in Go, Java, Microservices, Redis, and distributed systems.",
    skills: ["Java", "Go", "Spring Boot", "Microservices", "Kafka", "Redis", "MySQL", "Docker", "Kubernetes"],
    experience_years: 5.0,
    education: "B.Tech in Computer Science - NIT Surathkal (2019)",
    experience: [
      { company: "FinTech India Corp", role: "Backend Tech Lead", duration: "2021 - Present", description: "Architected real-time payment gateway processing 1M daily txns." }
    ],
    preferred_location: "Mumbai",
    preferred_work_type: "On-site",
    target_salary_min: 2400000,
    profile_completion: 80,
    resume_file: "Vikram_Malhotra_Backend.pdf"
  },
  {
    id: "cand_5",
    name: "Sneha Reddy",
    email: "sneha.reddy@example.com",
    target_role: "Frontend Engineer / UI Developer",
    summary: "Creative Frontend Developer with passion for React, Next.js, Framer Motion, and building pixel-perfect responsive user interfaces.",
    skills: ["React", "Next.js", "JavaScript", "TypeScript", "Tailwind CSS", "Redux Toolkit", "HTML5/CSS3", "Figma"],
    experience_years: 3.0,
    education: "B.Tech in CSE - BMS College Bangalore (2021)",
    experience: [
      { company: "CreativePixels", role: "Frontend Developer", duration: "2021 - Present", description: "Created responsive Web3 and SaaS web applications." }
    ],
    preferred_location: "Bangalore",
    preferred_work_type: "Hybrid",
    target_salary_min: 1400000,
    profile_completion: 90,
    resume_file: "Sneha_Reddy_Frontend.pdf"
  },
  {
    id: "cand_6",
    name: "Aditya Nair",
    email: "aditya.nair@example.com",
    target_role: "Data Engineer",
    summary: "Data Pipeline specialist skilled in Apache Spark, Snowflake, Airflow, PySpark, BigQuery, and Data Warehousing.",
    skills: ["Python", "SQL", "Apache Spark", "PySpark", "Snowflake", "Apache Airflow", "AWS Redshift", "ETL"],
    experience_years: 4.5,
    education: "B.E. in CSE - Anna University (2020)",
    experience: [
      { company: "DataNexus Systems", role: "Senior Data Engineer", duration: "2020 - Present", description: "Constructed petabyte-scale data pipelines using Spark and Airflow." }
    ],
    preferred_location: "Gurgaon",
    preferred_work_type: "Remote",
    target_salary_min: 2200000,
    profile_completion: 85,
    resume_file: "Aditya_Nair_DataEngineer.pdf"
  },
  {
    id: "cand_7",
    name: "Kavita Rao",
    email: "kavita.rao@example.com",
    target_role: "Product Analyst",
    summary: "Product Analyst with strong SQL, Tableau, Python, and Product Analytics background. Expert in A/B testing and cohort metrics.",
    skills: ["SQL", "Python", "Tableau", "Power BI", "Mixpanel", "A/B Testing", "Excel", "Product Analytics"],
    experience_years: 2.0,
    education: "B.Sc in Statistics - St. Xavier's Mumbai (2022)",
    experience: [
      { company: "GrowthMetrics", role: "Product Analyst", duration: "2022 - Present", description: "Analyzed funnel conversion rates and improved onboarding flow." }
    ],
    preferred_location: "Mumbai",
    preferred_work_type: "Hybrid",
    target_salary_min: 1200000,
    profile_completion: 75,
    resume_file: "Kavita_Rao_ProductAnalyst.pdf"
  },
  {
    id: "cand_8",
    name: "Devansh Gupta",
    email: "devansh.g@example.com",
    target_role: "DevOps / SRE Engineer",
    summary: "DevOps Specialist specializing in Terraform, AWS, Ansible, Kubernetes CI/CD automation, and infrastructure monitoring.",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Ansible", "Jenkins", "Prometheus", "Grafana", "Linux", "Bash"],
    experience_years: 4.0,
    education: "B.Tech in ECE - Manipal Institute (2020)",
    experience: [
      { company: "InfraCloud", role: "DevOps Engineer", duration: "2020 - Present", description: "Automated multi-region AWS cloud deployments with Terraform." }
    ],
    preferred_location: "Pune",
    preferred_work_type: "Remote",
    target_salary_min: 1900000,
    profile_completion: 90,
    resume_file: "Devansh_Gupta_DevOps.pdf"
  },
  {
    id: "cand_9",
    name: "Meera Joshi",
    email: "meera.j@example.com",
    target_role: "NLP Research Engineer",
    summary: "NLP Researcher specializing in Large Language Models, Transformers, HuggingFace, BERT, and Retrieval Augmented Generation (RAG).",
    skills: ["Python", "NLP", "Transformers", "PyTorch", "HuggingFace", "LangChain", "Vector Databases", "Scikit-Learn"],
    experience_years: 3.0,
    education: "M.S. in Computer Science - IIT Madras (2021)",
    experience: [
      { company: "Cognitive AI India", role: "NLP Scientist", duration: "2021 - Present", description: "Fine-tuned open source LLMs for specialized domain customer support." }
    ],
    preferred_location: "Bangalore",
    preferred_work_type: "Remote",
    target_salary_min: 2500000,
    profile_completion: 95,
    resume_file: "Meera_Joshi_NLP_Resume.pdf"
  },
  {
    id: "cand_10",
    name: "Tarun Kapoor",
    email: "tarun.k@example.com",
    target_role: "Cybersecurity Analyst",
    summary: "Cybersecurity & SOC analyst certified in CEH and CompTIA Security+. Passionate about network security and vulnerability assessments.",
    skills: ["Cybersecurity", "Network Security", "Ethical Hacking", "Python", "Wireshark", "SIEM", "Linux", "Penetration Testing"],
    experience_years: 2.0,
    education: "B.Tech in IT - Delhi Technological University (2022)",
    experience: [
      { company: "SecureTech Global", role: "Security Analyst", duration: "2022 - Present", description: "Monitored SIEM alerts and mitigated phishing attacks." }
    ],
    preferred_location: "Gurgaon",
    preferred_work_type: "On-site",
    target_salary_min: 1300000,
    profile_completion: 80,
    resume_file: "Tarun_Kapoor_CyberSec.pdf"
  }
];

export const initialJobs = [
  {
    id: "job_1",
    title: "Senior Data Scientist - AI & NLP",
    company: "NeuralPulse Tech",
    company_logo: "brain",
    location: "Bangalore",
    work_type: "Remote",
    experience_required: 3.0,
    required_skills: ["Python", "Machine Learning", "SQL", "NLP", "TensorFlow", "Scikit-Learn", "Pandas"],
    industry: "AI & Machine Learning",
    salary_range: "₹18,00,000 - ₹26,00,000 P.A.",
    description: "NeuralPulse is looking for an experienced Senior Data Scientist to lead our Recommendation and NLP teams. You will design, train, and deploy production ML models.",
    responsibilities: [
      "Develop scalable machine learning and NLP algorithms for recommendations",
      "Process large datasets using PySpark and SQL pipelines",
      "Collaborate with backend engineers to integrate Python microservices into web platforms",
      "Conduct A/B testing and model evaluation experiments"
    ],
    requirements: [
      "3+ years of commercial data science / ML experience",
      "Strong proficiency in Python, SQL, and Scikit-Learn / TensorFlow",
      "Hands-on experience with TF-IDF, embeddings, and text classification",
      "B.Tech/M.Tech in Computer Science or quantitative field"
    ],
    benefits: [
      "100% Remote flexibility",
      "Comprehensive Health Insurance",
      "Learning & Conference allowance",
      "Stock Options (ESOPs)"
    ],
    posted_date: "2026-10-01",
    status: "Active",
    recruiter_id: "rec_1"
  },
  {
    id: "job_2",
    title: "Full Stack Engineer (React + Node.js)",
    company: "Apex Enterprise SaaS",
    company_logo: "code",
    location: "Bangalore",
    work_type: "Hybrid",
    experience_required: 3.5,
    required_skills: ["React", "Node.js", "TypeScript", "Express", "PostgreSQL", "Tailwind CSS"],
    industry: "Software SaaS",
    salary_range: "₹16,00,000 - ₹24,00,000 P.A.",
    description: "Join Apex SaaS to build modern high-performance cloud applications. Work directly with cross-functional teams on web frontends and microservices.",
    responsibilities: [
      "Build sleek, accessible UI components in React and TypeScript",
      "Design and maintain scalable Express REST APIs and PostgreSQL schemas",
      "Ensure web app responsiveness and performance optimization"
    ],
    requirements: [
      "3+ years building production applications with Node.js and React",
      "Strong CSS skill with Tailwind CSS or styled-components",
      "Familiarity with Docker and AWS deployment pipeline"
    ],
    benefits: ["Hybrid Work arrangement", "Gym & Wellness Stipend", "Flexible Leave Policy"],
    posted_date: "2026-09-28",
    status: "Active",
    recruiter_id: "rec_1"
  },
  {
    id: "job_3",
    title: "AI / Machine Learning Engineer",
    company: "Acme AI Labs",
    company_logo: "sparkles",
    location: "Hyderabad",
    work_type: "Remote",
    experience_required: 2.0,
    required_skills: ["Python", "PyTorch", "Computer Vision", "FastAPI", "Docker", "MLOps"],
    industry: "Artificial Intelligence",
    salary_range: "₹20,00,000 - ₹28,00,000 P.A.",
    description: "Acme AI Labs is building autonomous vision systems. We need a passionate ML Engineer skilled in PyTorch, MLOps, and real-time model deployment.",
    responsibilities: [
      "Train deep learning models for image segmentation and classification",
      "Containerize ML models using Docker and deploy via FastAPI endpoints",
      "Optimize inference speed for GPU clusters"
    ],
    requirements: [
      "2+ years PyTorch or TensorFlow experience",
      "Demonstrated experience deploying ML pipelines to production",
      "Master's degree preferred"
    ],
    benefits: ["Cutting-edge hardware allowance", "Annual International Offsite"],
    posted_date: "2026-10-02",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_4",
    title: "Senior Backend Developer (Go / Java)",
    company: "PayFlow Digital",
    company_logo: "credit-card",
    location: "Mumbai",
    work_type: "On-site",
    experience_required: 4.5,
    required_skills: ["Java", "Go", "Spring Boot", "Microservices", "Kafka", "Redis", "MySQL"],
    industry: "Fintech",
    salary_range: "₹22,00,000 - ₹32,00,000 P.A.",
    description: "PayFlow Digital powers digital payments across Asia. Looking for a Backend Engineer to build resilient distributed payment gateways.",
    responsibilities: [
      "Design high-throughput microservices using Go and Java Spring Boot",
      "Manage event streaming architectures using Apache Kafka",
      "Optimize Redis cache layer and SQL query performance"
    ],
    requirements: [
      "4+ years backend development experience",
      "Deep understanding of distributed locks, ACID transactions, and system design"
    ],
    benefits: ["Performance Bonus", "Catered Meals", "Premium Medical Cover"],
    posted_date: "2026-09-25",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_5",
    title: "Frontend UI Developer (React / Next.js)",
    company: "PixelCraft Technologies",
    company_logo: "layout",
    location: "Bangalore",
    work_type: "Hybrid",
    experience_required: 2.5,
    required_skills: ["React", "Next.js", "JavaScript", "TypeScript", "Tailwind CSS", "Figma"],
    industry: "Consumer Web",
    salary_range: "₹14,00,000 - ₹20,00,000 P.A.",
    description: "Craft memorable digital experiences. Seeking a React developer with an eye for UI detail and modern web standards.",
    responsibilities: [
      "Implement design systems from Figma to React components",
      "Optimize web application page speed and Lighthouse scores"
    ],
    requirements: [
      "2+ years experience with React, Next.js, and modern CSS",
      "Strong JavaScript / TypeScript foundations"
    ],
    benefits: ["Hybrid schedule", "Latest MacBook Pro provided"],
    posted_date: "2026-10-03",
    status: "Active",
    recruiter_id: "rec_1"
  },
  {
    id: "job_6",
    title: "Big Data & Spark Engineer",
    company: "DataCloud Global",
    company_logo: "database",
    location: "Gurgaon",
    work_type: "Remote",
    experience_required: 4.0,
    required_skills: ["Python", "SQL", "Apache Spark", "PySpark", "Snowflake", "Apache Airflow", "ETL"],
    industry: "Data & Analytics",
    salary_range: "₹20,00,000 - ₹30,00,000 P.A.",
    description: "Build next-generation data warehouses and ETL pipelines handling petabytes of data.",
    responsibilities: [
      "Architect and maintain data pipelines using Spark and Airflow",
      "Optimize Snowflake query performance and data models"
    ],
    requirements: ["4+ years experience with PySpark, SQL, and cloud data warehouses"],
    benefits: ["Remote work", "Flexible work hours", "Annual learning stipend"],
    posted_date: "2026-09-29",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_7",
    title: "NLP Scientist - Large Language Models",
    company: "CognitiveAI Research",
    company_logo: "cpu",
    location: "Bangalore",
    work_type: "Remote",
    experience_required: 3.0,
    required_skills: ["Python", "NLP", "Transformers", "PyTorch", "HuggingFace", "LangChain"],
    industry: "AI Research",
    salary_range: "₹24,00,000 - ₹35,00,000 P.A.",
    description: "Join our core NLP lab to develop RAG systems, LLM fine-tuning, and domain-specific AI assistants.",
    responsibilities: [
      "Fine-tune Open Source LLMs (Llama, Mistral) on custom datasets",
      "Build RAG pipelines using LangChain and vector databases"
    ],
    requirements: ["Solid NLP background, PyTorch, and Transformers library experience"],
    benefits: ["Top-tier compensation", "GPU cluster access", "Patent bonuses"],
    posted_date: "2026-10-02",
    status: "Active",
    recruiter_id: "rec_1"
  },
  {
    id: "job_8",
    title: "DevOps & Cloud Infrastructure Specialist",
    company: "CloudScale Systems",
    company_logo: "server",
    location: "Pune",
    work_type: "Remote",
    experience_required: 3.5,
    required_skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Jenkins", "Prometheus"],
    industry: "Cloud Infrastructure",
    salary_range: "₹18,00,000 - ₹27,00,000 P.A.",
    description: "Manage and automate multi-cloud Kubernetes infrastructure for high availability.",
    responsibilities: ["Maintain Kubernetes clusters and automated CI/CD pipelines", "Implement Infrastructure as Code using Terraform"],
    requirements: ["3+ years DevOps experience with AWS and K8s"],
    benefits: ["Remote work", "Certification reimbursement"],
    posted_date: "2026-09-30",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_9",
    title: "Junior Data Analyst",
    company: "MarketMetrics",
    company_logo: "bar-chart",
    location: "Mumbai",
    work_type: "Hybrid",
    experience_required: 1.5,
    required_skills: ["SQL", "Python", "Tableau", "Excel", "A/B Testing"],
    industry: "Analytics",
    salary_range: "₹10,00,000 - ₹15,00,000 P.A.",
    description: "Analyze customer behavior data and present actionable business insights using SQL and Tableau.",
    responsibilities: ["Build automated Tableau dashboards", "Run cohort analysis and SQL queries"],
    requirements: ["Strong SQL skills and Tableau experience"],
    benefits: ["Mentorship program", "Career growth opportunities"],
    posted_date: "2026-10-01",
    status: "Active",
    recruiter_id: "rec_1"
  },
  {
    id: "job_10",
    title: "Cybersecurity Incident Specialist",
    company: "ShieldSec Global",
    company_logo: "shield",
    location: "Gurgaon",
    work_type: "On-site",
    experience_required: 2.0,
    required_skills: ["Cybersecurity", "Network Security", "Wireshark", "SIEM", "Python"],
    industry: "Cybersecurity",
    salary_range: "₹12,00,000 - ₹18,00,000 P.A.",
    description: "Monitor corporate SOC alerts and investigate security incidents.",
    responsibilities: ["Investigate SIEM alerts", "Perform vulnerability scanning"],
    requirements: ["CEH or Security+ certification preferred"],
    benefits: ["Comprehensive medical benefits", "On-site fitness center"],
    posted_date: "2026-09-27",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_11",
    title: "Lead Python Developer",
    company: "PyTech Labs",
    company_logo: "code-2",
    location: "Hyderabad",
    work_type: "Hybrid",
    experience_required: 5.0,
    required_skills: ["Python", "FastAPI", "Django", "PostgreSQL", "Docker", "Redis"],
    industry: "Software SaaS",
    salary_range: "₹25,00,000 - ₹36,00,000 P.A.",
    description: "Lead Python development team building high performance microservices.",
    responsibilities: ["Architect FastAPI microservices", "Mentor junior developers"],
    requirements: ["5+ years Python development experience"],
    benefits: ["Leadership role", "ESOPs"],
    posted_date: "2026-09-26",
    status: "Active",
    recruiter_id: "rec_1"
  },
  {
    id: "job_12",
    title: "React Native Mobile Engineer",
    company: "Appify Studios",
    company_logo: "smartphone",
    location: "Bangalore",
    work_type: "Remote",
    experience_required: 3.0,
    required_skills: ["React Native", "React", "JavaScript", "Redux", "iOS", "Android"],
    industry: "Mobile Apps",
    salary_range: "₹16,00,000 - ₹24,00,000 P.A.",
    description: "Develop cross-platform iOS and Android mobile apps in React Native.",
    responsibilities: ["Build mobile UI components", "Integrate native modules"],
    requirements: ["3+ years React Native experience"],
    benefits: ["Remote work", "Device allowance"],
    posted_date: "2026-09-29",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_13",
    title: "MLOps Engineer (CI/CD for Machine Learning)",
    company: "Acme AI Labs",
    company_logo: "sparkles",
    location: "Hyderabad",
    work_type: "Remote",
    experience_required: 3.0,
    required_skills: ["Python", "Docker", "Kubernetes", "MLOps", "MLflow", "Kubeflow", "AWS"],
    industry: "Artificial Intelligence",
    salary_range: "₹22,00,000 - ₹30,00,000 P.A.",
    description: "Automate ML model lifecycle from experimentation to production monitoring.",
    responsibilities: ["Set up Kubeflow / MLflow pipelines", "Monitor model drift"],
    requirements: ["3+ years MLOps / DevOps experience with Python"],
    benefits: ["Remote work", "Generous equity"],
    posted_date: "2026-10-02",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_14",
    title: "Database Administrator (PostgreSQL & Redis)",
    company: "PayFlow Digital",
    company_logo: "database",
    location: "Mumbai",
    work_type: "On-site",
    experience_required: 4.0,
    required_skills: ["PostgreSQL", "SQL", "Redis", "Linux", "Backup & Recovery"],
    industry: "Fintech",
    salary_range: "₹18,00,000 - ₹26,00,000 P.A.",
    description: "Manage enterprise PostgreSQL databases and Redis caching servers.",
    responsibilities: ["Database tuning", "Replication & Disaster recovery setup"],
    requirements: ["4+ years PostgreSQL DBA experience"],
    benefits: ["On-site perks", "Health cover"],
    posted_date: "2026-09-24",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_15",
    title: "Product Manager - AI Products",
    company: "NeuralPulse Tech",
    company_logo: "brain",
    location: "Bangalore",
    work_type: "Hybrid",
    experience_required: 4.0,
    required_skills: ["Product Management", "AI/ML", "Agile", "User Research", "SQL"],
    industry: "AI Technology",
    salary_range: "₹25,00,000 - ₹38,00,000 P.A.",
    description: "Drive product strategy and roadmap for AI recommendation services.",
    responsibilities: ["Define feature requirements", "Work closely with DS and Engineering teams"],
    requirements: ["4+ years PM experience in tech products"],
    benefits: ["Competitive package", "Stock options"],
    posted_date: "2026-10-03",
    status: "Active",
    recruiter_id: "rec_1"
  },
  {
    id: "job_16",
    title: "Computer Vision Specialist",
    company: "Acme AI Labs",
    company_logo: "sparkles",
    location: "Hyderabad",
    work_type: "Remote",
    experience_required: 3.5,
    required_skills: ["Python", "PyTorch", "OpenCV", "Computer Vision", "Deep Learning"],
    industry: "Artificial Intelligence",
    salary_range: "₹24,00,000 - ₹34,00,000 P.A.",
    description: "Develop SOTA vision algorithms for video analytics.",
    responsibilities: ["Develop object tracking algorithms", "Train YOLOV8 models"],
    requirements: ["Strong background in Computer Vision and PyTorch"],
    benefits: ["Remote work", "Conference travel"],
    posted_date: "2026-10-01",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_17",
    title: "Cloud Security Architect",
    company: "ShieldSec Global",
    company_logo: "shield",
    location: "Gurgaon",
    work_type: "Hybrid",
    experience_required: 6.0,
    required_skills: ["AWS", "Cloud Security", "Cybersecurity", "Terraform", "Compliance"],
    industry: "Cybersecurity",
    salary_range: "₹30,00,000 - ₹45,00,000 P.A.",
    description: "Architect cloud security postures and compliance frameworks for global enterprise clients.",
    responsibilities: ["Review cloud architectures", "Enforce security standards"],
    requirements: ["6+ years experience in Cloud Security"],
    benefits: ["Executive package", "Flexibility"],
    posted_date: "2026-09-22",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_18",
    title: "QA Automation Engineer (Selenium & Cypress)",
    company: "Apex Enterprise SaaS",
    company_logo: "check-circle",
    location: "Bangalore",
    work_type: "Hybrid",
    experience_required: 2.5,
    required_skills: ["JavaScript", "Python", "Selenium", "Cypress", "Git", "CI/CD"],
    industry: "Software SaaS",
    salary_range: "₹12,00,000 - ₹18,00,000 P.A.",
    description: "Write automated end-to-end regression test suites for web applications.",
    responsibilities: ["Create Cypress test suites", "Integrate automated tests into GitHub Actions"],
    requirements: ["2+ years automation testing experience"],
    benefits: ["Hybrid work", "Learning stipend"],
    posted_date: "2026-09-28",
    status: "Active",
    recruiter_id: "rec_1"
  },
  {
    id: "job_19",
    title: "Staff Data Engineer - Streaming Systems",
    company: "DataCloud Global",
    company_logo: "database",
    location: "Bangalore",
    work_type: "Remote",
    experience_required: 6.0,
    required_skills: ["Python", "Apache Kafka", "Flink", "Spark", "SQL", "Scala", "AWS"],
    industry: "Data & Analytics",
    salary_range: "₹32,00,000 - ₹48,00,000 P.A.",
    description: "Lead real-time streaming infrastructure for high velocity event streams.",
    responsibilities: ["Architect Kafka & Flink pipelines", "Set up real-time analytics engine"],
    requirements: ["6+ years data engineering with streaming tech"],
    benefits: ["Top tier ESOP package", "Remote"],
    posted_date: "2026-09-20",
    status: "Active",
    recruiter_id: "rec_2"
  },
  {
    id: "job_20",
    title: "Full Stack Engineer (Python + Vue.js)",
    company: "Innovate Solutions",
    company_logo: "layers",
    location: "Pune",
    work_type: "Hybrid",
    experience_required: 3.0,
    required_skills: ["Python", "FastAPI", "Vue.js", "JavaScript", "PostgreSQL", "Tailwind CSS"],
    industry: "Software Engineering",
    salary_range: "₹15,00,000 - ₹22,00,000 P.A.",
    description: "Develop internal tools and customer facing web applications.",
    responsibilities: ["Build Vue.js UI", "Write FastAPI REST endpoints"],
    requirements: ["3+ years Python & Vue.js experience"],
    benefits: ["Hybrid schedule", "Health insurance"],
    posted_date: "2026-09-30",
    status: "Active",
    recruiter_id: "rec_1"
  }
];

export const initialApplications = [
  {
    id: "app_101",
    candidate_id: "cand_1",
    job_id: "job_1",
    job_title: "Senior Data Scientist - AI & NLP",
    company: "NeuralPulse Tech",
    applied_date: "2026-10-02",
    updated_at: "2026-10-03",
    status: "Interview",
    match_score: 94,
    notes: "Interview scheduled for Oct 6th with VP of AI Engineering."
  },
  {
    id: "app_102",
    candidate_id: "cand_1",
    job_id: "job_3",
    job_title: "AI / Machine Learning Engineer",
    company: "Acme AI Labs",
    applied_date: "2026-10-02",
    updated_at: "2026-10-02",
    status: "Under Review",
    match_score: 91,
    notes: "Resume shared with Hiring Manager."
  },
  {
    id: "app_103",
    candidate_id: "cand_1",
    job_id: "job_7",
    job_title: "NLP Scientist - Large Language Models",
    company: "CognitiveAI Research",
    applied_date: "2026-10-03",
    updated_at: "2026-10-03",
    status: "Applied",
    match_score: 96,
    notes: "Application received."
  },
  {
    id: "app_104",
    candidate_id: "cand_1",
    job_id: "job_15",
    job_title: "Product Manager - AI Products",
    company: "NeuralPulse Tech",
    applied_date: "2026-09-28",
    updated_at: "2026-09-30",
    status: "Rejected",
    match_score: 65,
    notes: "Role requires candidate with direct PM experience."
  },
  {
    id: "app_105",
    candidate_id: "cand_2",
    job_id: "job_2",
    job_title: "Full Stack Engineer (React + Node.js)",
    company: "Apex Enterprise SaaS",
    applied_date: "2026-09-29",
    updated_at: "2026-10-01",
    status: "Offer",
    match_score: 95,
    notes: "Offer extended! Waiting for acceptance."
  },
  {
    id: "app_106",
    candidate_id: "cand_3",
    job_id: "job_3",
    job_title: "AI / Machine Learning Engineer",
    company: "Acme AI Labs",
    applied_date: "2026-10-03",
    updated_at: "2026-10-03",
    status: "Interview",
    match_score: 98,
    notes: "Technical coding round completed."
  },
  {
    id: "app_107",
    candidate_id: "cand_4",
    job_id: "job_4",
    job_title: "Senior Backend Developer (Go / Java)",
    company: "PayFlow Digital",
    applied_date: "2026-09-26",
    updated_at: "2026-09-28",
    status: "Under Review",
    match_score: 92,
    notes: "System design assessment pending."
  },
  {
    id: "app_108",
    candidate_id: "cand_5",
    job_id: "job_5",
    job_title: "Frontend UI Developer (React / Next.js)",
    company: "PixelCraft Technologies",
    applied_date: "2026-10-03",
    updated_at: "2026-10-04",
    status: "Under Review",
    match_score: 93,
    notes: "Portfolio under evaluation."
  }
];

export const initialRecruiters = [
  {
    id: "rec_1",
    name: "Dr. Vikram Sethi",
    email: "vikram.sethi@neuralpulse.ai",
    company: "NeuralPulse Tech",
    role: "Head of AI Talent Acquisition",
    location: "Bangalore"
  },
  {
    id: "rec_2",
    name: "Ananya Deshmukh",
    email: "ananya.d@acmeai.com",
    company: "Acme AI Labs",
    role: "Senior Tech Recruiter",
    location: "Hyderabad"
  }
];
